FROM php:7.4-cli-alpine

ADD entrypoint.sh /entrypoint.sh

RUN apk add --no-cache bash && \
    chmod +x /entrypoint.sh && \
    chown -R nobody:nobody /entrypoint.sh

USER nobody

CMD /entrypoint.sh
VOLUME /code
